services:
  - type: web
    name: fantasy-sports-analytics
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production